### ISSUE TITLE
Lazy load data

### ISSUE THREAD

**Issue by krlmlr** [johnmyleswhite/ProjectTemplate#126]
Optionally, with the help of `delayedAssign()`.

**Comment by krlmlr** [comment]
Can't peek into `.rda` files. Create a package for each data set to benefit from lazy loading.

**Comment by lf-araujo** [comment]
A relatively simple way to add a lazy loading approach to data is use lazy_dt() when data.table is used as the data format in options. https://dtplyr.tidyverse.org/
