### ISSUE TITLE
url.reader not found

### ISSUE THREAD

**Issue by iembry-USGS** [johnmyleswhite/ProjectTemplate#135]
Hi, when I attempted to use the url.reader function, I came across an error.

See below:
library(ProjectTemplate) # version 0.6
url.reader('example.url', 'data/example.url', 'example')

Error: could not find function "url.reader"

Thank you.

**Comment by krlmlr** [comment]
This is pretty much by design -- the function is not exported but called implicitly in `load.project()`, although the documentation really suggests otherwise. The intended use case is to create a `.url` file in your project's `data` directory which is then processed when the project is loaded.

**Comment by iembry-USGS** [comment]
OK, thank you for letting me know.

Can you include what you've written on the url.reader help page?

Thank you again.
