### ISSUE TITLE
Initialise logger first

### ISSUE THREAD

**Issue by Hugovdberg** [johnmyleswhite/ProjectTemplate#150]
Currently the logger is intialised after the munging scripts are run. However, this means that any munging scripts (or even helper scripts) cannot access the logger. To me it seems it would make more sense to intitialise the log4r object before the helper functions are called, or at least load the library first if logging is enabled.

Some situations where this is useful:

- Using a helper script to transform very raw data into data that can be automatically loaded by ProjectTemplate, it can be very useful to output some debugging data
- Merging datasets in a munging script, I would like to be able to log (partially) failed joins to a logfile

Perhaps it would be useful to split the logs to separate files (for example "helper.log", "munge.log", "project.log") so current functionality isn't affected.

**Comment by KentonWhite** [comment]
@Hugovdberg This is a great idea. I don't personally use the logger so have never discovered this. I don't see any reason why the logger shouldn't be initialized before any work is done.

Do you feel comfortable changing where the logger object is initialized and making a pull request with the changes?

We can also discuss more why you feel having different log files would be necessary? For me a view everything that I do within the ProjectTemplate environment, including helper functions and munging, as part of "the project". Having a list of which munging and helper files I used in the project.log file might be advantageous! But again, I don't use the login function... perhaps there is some subtle difference I am overlooking?

**Comment by Hugovdberg** [comment]
I've never edited an R package before, but once has to be the first time so I'll give it a shot later this week. I've looked at the R code where the edit should be made, but I'm not sure if the `load.project.R` is the only thing that needs editing. I'll dive into it and see what I can do.

Regarding the different logfiles, my thinking was that perhaps you might want to separate the more low-level messages of the pre-processing for preparing the data for your analysis from the analysis itself. On the other hand I do see where you're coming from, and it could be interesting to log all messages to the log. If we implement that it is perhaps good to log those messages as DEBUG level messages, and allow setting the default loglevel from the `global.dcf` (which is now fixed to default at INFO).

Changing the automatic logging is somewhat more complex so is perhaps better to think this through some more before making it to complicated ;-) I think this package should automate a lot without too much flexibility as everyone will want other things to be flexible. If the `log4r` package is already loaded before the helper scripts people can always instantiate a secondary logger, especially if the `log4r` package would become a [wrapper of `logging`](https://github.com/johnmyleswhite/log4r/issues/3).

**Comment by KentonWhite** [comment]
Thanks! Think allowing a person to change the logging level is the correct path. It lets us leverage the features of log4r without needing to write more code.

**Comment by Hugovdberg** [comment]
Ok, I'll see what I can do, so if I understand you correctly the preferred way to implement this is as follows:

- add `logging_level` to `global.cdf` (allowing any valid string for the `log4r` package, with default at "INFO")
- Move logger initialisation in `load.project` to directly follow loading packages
- Set default loglevel to `logging_level` from config

Do you agree?

**Comment by Hugovdberg** [comment]
An extra argument in favour of adding the `logging_level` setting is that it can be overridden easily to output DEBUG messages.

**Comment by KentonWhite** [comment]
I agree. Let me know if you need any help with this, and thanks in advance!
