### ISSUE TITLE
Ignore files in data folder

### ISSUE THREAD

**Issue by Hugovdberg** [johnmyleswhite/ProjectTemplate#153]
How do you guys feel about adding an ignore list for file in `data/` to the configuration? A specific problem that occurs to me rather frequently is that at my workplace we're using windows, which creates Thumbs.db files as soon as a thumbnail is created.
Unfortunately, depending on the data files used, this is also created in the `data/` folder, after which the `load.project` treats it as a SQLite database, which it is not, and so it raises an error. On top of that, windows is notorious for keeping files locked, especially those thumbnail databases, and so deleting that file is often not an option. I can prevent windows from creating those files for myself, but I cannot force all my collegues to change their settings, so it is something I have to live with.

Now I see two possible solutions:
1. A hardcoded ignore of any `Thumbs.db`
2. An ignore list in the configuration that lets people ignore the files they want.

I think the latter is the most elegant, as for some people `Thumbs.db` could possibly be the file they want to import, and it also could speed up data loading if not all data is necessary in all stages of the project.

**Comment by KentonWhite** [comment]
Since I don't work on windows, I've never encountered this problem -- which is why open source is so awesome! Such a common problem for so many users and such a simple solution.

@Hugovdberg do you think you could put together a simple PR with the ignore list and adding `Thumbs.db` to the default list?

**Comment by Hugovdberg** [comment]
I can definitely create the code to do this, I was just wondering if the team would be interested to incorporate the code versus keeping it lean and clean. Are there other files or directories that might be created by an operating system automatically which we wish to exclude by default? I know I've seen some `.DS_Store`/`.Trash` files from Mac OS but I'm not sure when and where these are created so if they ever show up in a `data` directory.

**Comment by KentonWhite** [comment]
Files like `.DS_Store` and `.Trash` are all hidden files. Is the `Thumbs.db` also a hidden file on Windows (don't know enough about the OS). If `Thumbs.db` is also a hidden file, might it an alternative solution be to ignore hidden files?

**Comment by Hugovdberg** [comment]
`Thumbs.db` is hidden indeed, so it's a viable option to ignore hidden files, if it is possible to reliably detect hidden files across all operating systems. I will see what I can do on that. It would better fit the convention over configuration philosophy of the project, even though configuration in this case could drastically improve performance of analyses of subsets of the project data.

**Comment by connectedblue** [comment]
My suggestion would be a `dataignore` file in the data directory which has a list of regular expressions to ignore when reading the data.

The defaults directory could contain an example list of common defaults such as you've discussed already across all operating systems. Then it works out the box for most users without them having to do anything.


This fits the paradigm of `.gitignore` which I personally use in the top level directory to prevent data and cache objects behind written into git.

**Comment by KentonWhite** [comment]
Maybe it could read the `.gitignore` file. I'm assuming that many people include these files in their `.gitignore` file anyways.

**Comment by Hugovdberg** [comment]
Reading `.gitignore` isn't the best option I think. I sometimes include data in `.gitignore` if the data is compiled with a pre-preprocessing script in lib from a `data-raw` directory (and I see so does @connectedblue ). I often have a lot of separate files I want to combine into a single file for `ProjectTemplate` to read into memory, so there's no point in tracking that single file that can be reconstructed at all times. 
A `.dataignore` would be better, although I'm not sure if it's necessary. We could also include the specification in `global.dcf` to keep all configuration together in a single file, still providing the possibility to override it in a call to `load.project`. Using regex is a great idea by the way!

**Comment by connectedblue** [comment]
I think I prefer dataignore without the dot so it's always visible. It doesn't need to be a hidden file and would be more transparent to users.

I also don't think reading .gitignore is a good idea, because not everyone uses git!

**Comment by Hugovdberg** [comment]
But then again, why a separate configuration if it can be set through the single configuration file everyone is used to? Also, `dataignore` is then another reserved name (besides `config` and `logger`) for variable names. Also if people would already have a dataignore file in their datafolder it would now be mistakenly treated as special file, so I'm still for adding it to `global.dcf`.

**Comment by connectedblue** [comment]
@Hugodvberg `global.dcf` is also a good idea to keep all project template config in one place.  A comma separated list would be all you need.

**Comment by connectedblue** [comment]
Yes, agreed:) my comment crossed with yours!

**Comment by Hugovdberg** [comment]
I'll keep working on my current change then, expect a PR soon :)

**Comment by Hugovdberg** [comment]
Wow, it's taking a little longer than expected, didn't have as much time to donate as I had hoped.
Currently the following patterns can be ignored in my private repository (not yet ready for PR):
- Full filename (relative to `data/`): `Thumbs.db`, `subdir/ignore.csv`
- Wildcards in filenames using `*`: `*.xml`, `test-*.csv` (all other regex specials are escaped unless in a delimited regex)
- regular expressions, delimited by `/` in front and after: `/^\./` (ignores all hidden files on Un*x)
- Entire subdirectories can be ignored by adding only a trailing slash: `subdir/`

Currently my default `data_ignore` setting in `global.dcf` is: `Thumbs,db, /^\./`, so `Thumbs.db` for Windows and hidden files on Un*x.

Any obvious cases I missed which should be included before submitting the PR?

**Comment by connectedblue** [comment]
Sounds pretty comprehensive to me @Hugovdberg .  If people come up with new examples of files that exist on operating systems, I would think they could be added to the default template using the patterns you have designed.

As a convenience to the user, it could be good to put out a message when there is a match showing the filename that was skipped.

**Comment by KentonWhite** [comment]
Hi @Hugovdberg, looks pretty good to me as well. If you can submit as  PR and we'll merge into the master branch if all is good.

Can you think about adding some test cases to cover this behavior? It will help our future selves track down broken behavior :)  

I see this as an advanced feature, one where most people will be happy with the defaults working without even being aware it is there. If you have time (and I know that time can be in very short supply) it would be nice to have a little bit of documentation in the markdown docs in the `website` folder!

**Comment by Hugovdberg** [comment]
Closed, implemented by PR #178
