### ISSUE TITLE
.RData vs .Rdata

### ISSUE THREAD

**Issue by eribul** [johnmyleswhite/ProjectTemplate#190]
This might not be a bug but I had some trouble to get it to work so mayby the documentation could be clearer. 

I often work with projects where I need to rely on output from other pesople and projects. I often use .RData files found on a server. According to http://projecttemplate.net/file_formats.html, I could then have a .file-file like:

```
path: /bla/bla/bla
extension: .RData
```

Problem is that ".RData" must be written ".Rdata" (capital R but lower case "d"), which was at first not really clear to me. Could it be possible to just ignore case or to at least allow any of the two versions?

**Comment by KentonWhite** [comment]
@eribul I've made what I think should fix your problem.  It is currently on the master branch of Github.  Can you try out the new code and let me know if it fixes your report problem.

**Comment by eribul** [comment]
Thanks! Workd great!

tis 4 apr. 2017 kl 16:21 skrev Kenton White <notifications@github.com>:

**Comment by Hugovdberg** [comment]
@KentonWhite This issue should be closed.
