### ISSUE TITLE
Replace dplyr, ggplot2, stringr with tidyverse

### ISSUE THREAD

**Issue by rsangole** [johnmyleswhite/ProjectTemplate#205]
What are your thoughts in replacing these individual packages with tidyverse? Today, tidyverse will automatically import the core tidyverse packages:
    ggplot2, for data visualisation.
    dplyr, for data manipulation.
    tidyr, for data tidying.
    readr, for data import.
    purrr, for functional programming.
    tibble, for tibbles, a modern re-imagining of data frames.

Anyone working in the 'dplyr' / 'Hadley' framework pretty much requires all of these packages for every project.

**Comment by KentonWhite** [comment]
I happy with that idea.  It should be simply a matter of changing the default config file in the `inst` directory.  Would this be something you could make a pull request for?

**Comment by rsangole** [comment]
Yep, simple enough. I'll get it done today.

**Comment by rsangole** [comment]
@KentonWhite I'd also like to propose shifting from reshape to reshape2 given the performance increases in Hadley's package.

**Comment by KentonWhite** [comment]
That is a good idea.
