### ISSUE TITLE
Use Environment variables for sensitive information

### ISSUE THREAD

**Issue by KentonWhite** [johnmyleswhite/ProjectTemplate#30]
Some of the readers, like the SQL readers, require password information. Currently this is stored directly in the data file. Storing passwords in files is a security risk -- they can be checked into repositories or made accessible to the public.

Other communities use environment variables to store sensitive information. Can you do this in ProjectTemplate?

**Comment by kezkankrayon** [comment]
In the .sql file, it'd be great to be able to do the following:

`user: Sys.getenv("uid") `
`password: Sys.getenv("pwd")
`

Unfortunately, these are read as literal strings.
