### ISSUE TITLE
.sql files should be SQL, not DCF

### ISSUE THREAD

**Issue by lrcg** [johnmyleswhite/ProjectTemplate#72]
Files in `config/` are `.dcf`, but files in other directories are as well. This is not good. For example, according to the documentation,

 > .sql: A DCF file that contains database connection information for a MySQL database.

but the OS and other programmes will see this as a file containing SQL code. A project maintainer may want to have SQL code in `.sql` files to keep it out of `R` code and also share it with other programmes. It doesn't make sense to redefine all these file types just for the convenience of the framework.

A better solution would be `foo.sql.dcf`. That way the _format_ of the file is clearly the same as that in `config/`, but it's also clear to humans and the framework that it deals with the _configuration_ of loading databases.

The same would go for `.url` and `.file`.

**Comment by krlmlr** [comment]
I'll be happy to incorporate a pull request.
